server:
  port: 8084

spring:
  application:
    name: reservation-service
  config:
    import: "optional:configserver:http://localhost:8081"

management:
  tracing:
    sampling:
      probability: 1.0